
         <div class="row">
          <!--Textos da section-->
          <div class="col-md-6 d-flex text-white">
            <div class="align-self-center">
              <h1 class="display-4">Suas contas, descomplicadas</h1>
              <p>Usado por mais de 1 milhão de pessoas, o Finans é uma ferramenta online que vai facilitar sua vida financeira</p>
              <form class="mt-4 mb-4" action="">
                <div class="input-group input-group-lg">
                  <input class="form-control"type="text" name="" placeholder="Seu e-mail" id="">
                  <div class="input-group-append">
                    <buton class="btn btn-primary">Cadastre-se</buton>
                  </div>
                </div>
              </form>
              <p>Disponível para
                <a class="btn btn-outline-light"href="#">
                  <i class="fab fa-android fa-lg"></i>
                </a>
                <a class="btn btn-outline-light"href="#">
                  <i class="fab fa-apple fa-lg"></i>
                </a>
              </p>
            </div>
          </div>
          <div class="col-md-6 d-none d-md-block">
            <img src="./img/capa-mulher.png" alt="">
          </div>
        </div>
      <!--Fim Section-->