<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<!-- Font Awesome-->
		<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

		<!-- Estilos personalizados -->
		<link rel="stylesheet" href="css/home.css">
		<link rel="stylesheet" href="css/global.css">

		<link rel="stylesheet" type="text/css" href="/css/style.css">

	</head>

	<body>
		<header><!--Inicio do cabecalho -->
			<nav class="navbar navbar-expand-sm navbar-ligh bg-warning">
				<div class="container">
					<a href="#" class="navbar-brand">Imagem</a>

					<!--Botão collapse responsivo -->
					<button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
						<span class="navbar-toggler-icon"></span>
					</button>
					<!-- Menu de navegação -->
					<div class="collapse navbar-collapse" id="nav-principal">
						<ul class="navbar-nav ml-auto menu-navegacao align-items-center">
							<li class="nav-item">
								<a href="/" class="nav-link">Home</a>
							</li>
							<li class="nav-item">
								<a href="/produtos" class="nav-link">Produtos</a>
							</li>
							<li class="nav-item">
								<a href="#" class="nav-link">Quem somos</a>
							</li>
							<li class="nav-item">
								<a href="#" class="nav-link">Local</a>
							</li>
						</ul>
					</div>
					
				</div>
			</nav>
		</header>
		<!-- Fim header-->
		<section id="home">
			<div class="container">
				<?= $this->content() ?>
			</div>
		</section>
		



		<!--FOOTER-->
		<footer class="mt-4 mb-4 ">
			<div class="container">
				<div class="row">
					<div class="col-md-8">
						<p>
							<a href="">Home</a>
							<a href="">Recursos</a>
							<a href="">Benefícios</a>
							<a href="">Preço</a>

						</p>
					</div>
					<div class="col-md-4 d-flex justify-content-center">
						<a class="btn btn-outline-dark ml-2"href="#">
							<i class="fab fa-youtube fa-lg"></i>
						</a>
						<a class="btn btn-outline-dark ml-2"href="#">
							<i class="fab fa-facebook fa-lg"></i>
						</a>
						<a class="btn btn-outline-dark ml-2"href="#">
							<i class="fab fa-twitter fa-lg"></i>
						</a>
						<a class="btn btn-outline-dark ml-2"href="#">
							<i class="fab fa-instagram fa-lg"></i>
						</a>

					</div>
				</div>
			</div>
  </footer>





		<!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</body>

</html>